import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { 
  Download, 
  Edit3, 
  Share2, 
  FileText, 
  CheckSquare, 
  Users, 
  CreditCard, 
  Target, 
  Milestone, 
  Coins, 
  AlertTriangle, 
  ArrowRight
} from 'lucide-react';
import { useJourneyStore, ResultsData } from '../stores/useJourneyStore';

interface CardInfo {
  title: string;
  key: keyof ResultsData;
  icon: any;
  description: string;
}

const CARDS_CONFIG: CardInfo[] = [
  { 
    title: 'Startup Summary', 
    key: 'summary', 
    icon: FileText, 
    description: 'High-level overview of the venture concept.' 
  },
  { 
    title: 'Problem Validation', 
    key: 'validation', 
    icon: CheckSquare, 
    description: 'Direct methods to verify customer pain points.' 
  },
  { 
    title: 'Target Customers', 
    key: 'customers', 
    icon: Users, 
    description: 'The specific customer segments experiencing the pain.' 
  },
  { 
    title: 'Revenue Model', 
    key: 'revenue', 
    icon: CreditCard, 
    description: 'Primary monetization and business strategies.' 
  },
  { 
    title: 'Competitors', 
    key: 'competitors', 
    icon: Target, 
    description: 'Market landscape and differentiation positioning.' 
  },
  { 
    title: 'MVP Roadmap', 
    key: 'roadmap', 
    icon: Milestone, 
    description: 'The tactical steps to build and launch.' 
  },
  { 
    title: 'Funding Options', 
    key: 'funding', 
    icon: Coins, 
    description: 'Funding avenues matched to the budget and stage.' 
  },
  { 
    title: 'Risks', 
    key: 'risks', 
    icon: AlertTriangle, 
    description: 'Critical market, technical, and operational hurdles.' 
  },
  { 
    title: 'Next Actions', 
    key: 'actions', 
    icon: ArrowRight, 
    description: 'Immediate, actionable next steps for execution.' 
  }
];

const containerVariants = {
  hidden: { opacity: 0 },
  show: {
    opacity: 1,
    transition: {
      staggerChildren: 0.08
    }
  }
};

const cardVariants = {
  hidden: { opacity: 0, y: 30 },
  show: { 
    opacity: 1, 
    y: 0, 
    transition: { 
      type: 'spring',
      stiffness: 100,
      damping: 15
    } 
  }
};

export function ResultsWorkspace() {
  const navigate = useNavigate();
  const { results, inputs } = useJourneyStore();

  if (!results) {
    return (
      <div className="act-results-empty">
        <p>No analysis results found.</p>
        <button onClick={() => navigate('/')}>Go to Home</button>
      </div>
    );
  }

  const handleShare = () => {
    if (navigator.clipboard) {
      navigator.clipboard.writeText(window.location.href);
      alert('Workspace link copied to clipboard!');
    }
  };

  return (
    <div className="act-results-shell">

      {/* Sticky Header */}
      <header className="act-results-header">
        <div className="act-results-header__left">
          <span className="act-label" style={{ marginBottom: 0 }}>Execution Workspace</span>
          <p className="act-results-header__idea">{inputs.idea}</p>
        </div>
        <div className="act-results-header__actions">
          <button onClick={() => navigate('/input')} className="act-results-action-btn">
            <Edit3 size={14} strokeWidth={1.5} /> Edit inputs
          </button>
          <button onClick={handleShare} className="act-results-action-btn">
            <Share2 size={14} strokeWidth={1.5} /> Share
          </button>
          <button onClick={() => window.print()} className="act-results-action-btn act-results-action-btn--accent">
            <Download size={14} strokeWidth={1.5} /> Export PDF
          </button>
        </div>
      </header>

      <main className="act-results-main">

        {/* ── Welcome Banner ── */}
        <section className="act-score-hero" style={{ marginBottom: '3rem' }}>
          <div className="act-score-hero__inner">
            <div className="act-reason-panel">
              <span className="act-reason-panel__eyebrow">Advisor Insights</span>
              <strong>Practical, execution-focused advice generated by IdeaBridge AI.</strong>
              <p>
                The workspace structures key strategic pillars for your startup based on your target market, budget level, and constraints.
              </p>
            </div>
            <div className="act-score-hero__copy">
              <span className="act-label">Launch Strategy</span>
              <h1 className="act-score-hero__heading" style={{ fontSize: 'clamp(1.5rem, 3vw, 2.5rem)', lineHeight: 1.2 }}>
                Custom Startup Execution Blueprint
              </h1>
              <p className="text-neutral-400 mt-2 text-sm">
                Targeting <strong>{inputs.audience}</strong> within the <strong>{inputs.industry}</strong> sector in <strong>{inputs.country}</strong>, optimized for a <strong>{inputs.budget}</strong> budget and a team of <strong>{inputs.teamSize}</strong>.
              </p>
            </div>
          </div>
        </section>

        {/* ── 9-Card Animated Grid ── */}
        <motion.div 
          className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6"
          variants={containerVariants}
          initial="hidden"
          animate="show"
        >
          {CARDS_CONFIG.map((card) => {
            const Icon = card.icon;
            // Fallback to "Information unavailable." if missing
            const bulletPoints = (results as any)[card.key] || ['Information unavailable.'];

            return (
              <motion.div
                key={card.key}
                variants={cardVariants}
                className="glass-panel--elevated border border-white/5 bg-[#0d0d0d]/80 rounded-xl p-6 hover:border-[#00f0ff]/30 transition-all duration-300 flex flex-col group"
                style={{ backdropFilter: 'blur(10px)' }}
              >
                <div className="flex items-center gap-3 mb-3">
                  <div className="p-2 bg-[#00f0ff]/5 rounded-lg text-[#00f0ff] group-hover:bg-[#00f0ff]/10 transition-colors">
                    <Icon size={20} strokeWidth={1.5} />
                  </div>
                  <h3 className="font-semibold text-lg text-white group-hover:text-[#00f0ff] transition-colors">
                    {card.title}
                  </h3>
                </div>
                
                <p className="text-xs text-neutral-500 mb-4 leading-relaxed">
                  {card.description}
                </p>

                <div className="flex-1 flex flex-col justify-start">
                  <ul className="space-y-3">
                    {bulletPoints.map((point: string, index: number) => (
                      <li key={index} className="flex gap-2 text-sm text-neutral-300 leading-relaxed alignment-start">
                        <span className="text-[#00f0ff] font-bold mt-0.5">•</span>
                        <span>{point}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </motion.div>
            );
          })}
        </motion.div>

        {/* ── Footer CTA ── */}
        <div className="act-results-divider" />
        <div className="act-results-footer">
          <p>Ready to refine your startup plan?</p>
          <button onClick={() => navigate('/input')} className="act-cta-btn">
            Refine Inputs →
          </button>
        </div>

      </main>
    </div>
  );
}

